toebes/ciphers

- app/codebusters/ciphertestresults.ts
- app/common/cipherhandler.ts
- app/common/styles.css
Refactor the scoring code to use setTimeout()...
> Scoring refactor

- app/codebusters/ciphertestschedule.ts
- app/common/cipherhandler.ts
Fix CSV import and processes all test takers
> Fixes #243 #251

- app/codebusters/cipherfactory.ts
- app/codebusters/cipherrsaencoder.ts
- app/codebusters/interactiversaencoder.ts
Formatting of the input field needs some CSS magic.  Functionally, seems to work OK.
> Add support for RSA interactive tests.

- app/codebusters/ciphertestresults.ts
- app/codebusters/ciphertestscorer.ts
1. Updated CSV format as discussed.  
1. Integrated natural sorting on Score column (tiebreaks with decimals don't quite work right).  
1. Disable export CVS button until done calculating.
1. Cleanup
> Platformupdates

- app/codebusters/cipherhillencoder.ts
- app/codebusters/cipherrsaencoder.ts
- app/codebusters/ciphertestresults.ts
- app/codebusters/ciphertestscorer.ts
- app/common/cipherhandler.ts
- app/common/styles.css
> Special bonus

- app/codebusters/cipherfractionatedmorseencoder.ts
- app/codebusters/pages/TestGuidance.html
> [fractionated_morse] - just usable

- app/codebusters/cipherencoder.ts
- package-lock.json
Not sure if I'm doing this process right, but I created a 'tinker' branch with my fix commits for issue #384 and am now creating a pull request for the change. Let me know if I'm doing it wrong
> include encoding type (K1, etc.) in replacement suggestion text

- app/codebusters/ciphertest.ts
- app/codebusters/ciphertestgenerator.ts
additionally, small fix with respect to resetting general error test messages (for example getting rid of Div. C error messages when Div. B is selected)
> Merge fix for issue #383 (NO test type selection added)

- app/codebusters/ciphercompletecolumnarencoder.ts
- app/codebusters/ciphertest.ts
- app/codebusters/pages/TestGuidance.html
- app/common/ciphercommon.ts
- app/common/cipherhandler.ts
- app/common/styles.css
Merge Complete Columnar Initial Version
> Complete columnar

- app/codebusters/ciphernihilistsubstitutionencoder.ts
this was a request from a student - good suggestion
> added blank space between ciphertext lines

- app/codebusters/ciphernihilistsubstitutionencoder.ts
- app/common/styles.css
Issue #386 mostly completed (still a bit of touching up to do)
> Nihilist cryptanalysis solver implemented

- app/codebusters/ciphernihilistsubstitutionencoder.ts
- app/common/styles.css
Lots of work on issue #386, still a bit more to go
> work on nihilist cryptanalysis auto-solver

- app/codebusters/ciphernihilistsubstitutionencoder.ts
> fixed issue #499 where crib display got misaligned

- app/codebusters/ciphercryptarithmencoder.ts
- app/codebusters/ciphertestanswers.ts
- app/common/readability.ts
- package-lock.json
Fixed a bug where the solution to cryptarithms wasn't showing up on the tiny answer key.
> Tiny answer fix 525

- app/codebusters/pages/index.html
> Updated index.html

- app/codebusters/cipheraffineencoder.ts
Adds the option to give a block size for affines. Currently increases the points by 50, can be changed in the future.
> Block size for affine #534

- app/common/jtmenu.ts
Fixed the issue where when selecting Xenocrypt from the drop down menu, it doesn't set the language to Spanish
> Fixed issue #542

- app/codebusters/pages/TestGuidance.html
Updated references to ciphers in Div A to match this year's rules. Other minor tweaks.
> Update TestGuidance.html for Div A

- app/codebusters/cipherhillencoder.ts
Updated 3x3 points per letter to be more in line with 2x2
> Update Hill 3x3 scoring

- app/codebusters/cipheraristocratencoder.ts
- app/codebusters/cipherbaconianencoder.ts
- app/codebusters/ciphercryptarithmencoder.ts
- app/codebusters/cipherencoder.ts
- app/codebusters/ciphernihilistsubstitutionencoder.ts
- app/codebusters/cipherrailfenceencoder.ts
- app/codebusters/ciphertableencoder.ts
- app/codebusters/ciphervigenereencoder.ts
- app/common/styles.css
Finished implementing the random question text! Please let me know if you find any bugs or better functionality that I should add.
> Random question text #425

- app/codebusters/cipheraffineencoder.ts
- app/codebusters/cipherencoder.ts
- app/codebusters/cipherhillencoder.ts
- app/codebusters/ciphervigenereencoder.ts
This should fix the 4 issues mentioned in #580.
> Resolved issue #580

- app/codebusters/ciphervigenereencoder.ts
Fixed the bug with the Vigenère cipher not having an accent in the suggested question text.
> Fixed #586 Vigenere with no accent

- app/codebusters/cipherbaconianencoder.ts
Fixed the encodes vs encode issue in two suggested question options for Baconians.
> Fixed #592 grammar issue

- app/codebusters/ciphervigenereencoder.ts
Fixed the bug where Portas were displaying as Vigeneres in the suggested question text
> Fixed #600

- app/codebusters/ciphertestgenerator.ts
Fixes #629: show upper range of questions for test type and reword warning
> Fixes #629: show upper range of questions for test type and reword warning

- app/codebusters/ciphercheckerboardencoder.ts
- app/codebusters/pages/TestGuidance.html
- app/codebusters/pages/index.html
- Created crib suggestion generator
- Fix negative block size
> Checkerboard Crib Generator

- app/codebusters/ciphercheckerboardencoder.ts
- app/codebusters/ciphernihilistsubstitutionencoder.ts
- app/common/styles.css
#630: Fixes table header highlighting problem, now should better distinguish key words/headers from sequence in nihilist and checkerboard
> #630: Fixes table header highlighting problem, now should better distinguish key words/headers from sequence in nihilist and checkerboard
